### ISSUE TITLE
Get started screen desktop 

### ISSUE THREAD

**Issue by Manubi** [SerenityNotes/serenity-notes-clients#8]
Hi,

the _GetStarted_ screen on MacOS Big Sur looks like this. I do use dark mode. 

![CleanShot 2021-06-05 at 12 07 27](https://user-images.githubusercontent.com/20935138/120888101-d7ea1100-c5f6-11eb-9f8a-42194594f2b5.png)

**Comment by nikgraf** [comment]
ohh, thanks for the hint! will fix that asap

**Comment by nikgraf** [comment]
Fixed with this release https://github.com/SerenityNotes/serenity-notes-clients/releases/tag/v.0.2.0-beta
